definitions:
  dto.AddUser:
    properties:
      password:
        maxLength: 20
        minLength: 4
        type: string
      role_id:
        minimum: 0
        type: integer
      user_name:
        maxLength: 20
        minLength: 4
        type: string
    required:
    - password
    - user_name
    type: object
  dto.Auth:
    properties:
      password:
        maxLength: 20
        minLength: 4
        type: string
      user_name:
        maxLength: 20
        minLength: 4
        type: string
    required:
    - password
    - user_name
    type: object
  dto.CreateRole:
    properties:
      is_admin:
        type: boolean
      role_key:
        type: string
      role_name:
        type: string
    type: object
  response.JSONTime:
    properties:
      time.Time:
        type: string
    type: object
  response.Struct:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      time:
        $ref: '#/definitions/response.JSONTime'
    type: object
info:
  contact: {}
  title: Healthcare panel
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: User Login
      parameters:
      - description: user login
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.Auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Struct'
        "400":
          description: wrong request parameter
          schema:
            $ref: '#/definitions/response.Struct'
        "401":
          description: The corresponding username or password is incorrect
          schema:
            $ref: '#/definitions/response.Struct'
      summary: User Login
      tags:
      - Auth
  /role:
    post:
      consumes:
      - application/json
      description: Create role
      parameters:
      - description: role_id
        in: path
        name: role_id
        required: true
        type: integer
      - description: "YES"
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.CreateRole'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Struct'
        "400":
          description: wrong request parameter
          schema:
            $ref: '#/definitions/response.Struct'
      summary: Create role
      tags:
      - Role
  /user:
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: create new user
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.AddUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Struct'
        "400":
          description: wrong request parameter
          schema:
            $ref: '#/definitions/response.Struct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Struct'
      security:
      - ApiKeyAuth: []
      summary: create user
      tags:
      - User
swagger: "2.0"
